-- CreateTable
CREATE TABLE "Contract" (
    "id" SERIAL NOT NULL,
    "file" TEXT NOT NULL,
    "nrInst" TEXT NOT NULL,
    "nrAgencia" TEXT NOT NULL,
    "cdClient" TEXT NOT NULL,
    "nmClient" TEXT NOT NULL,
    "nrCpfCnpj" TEXT NOT NULL,
    "nrContrato" TEXT NOT NULL,
    "dtContrato" TIMESTAMP(3) NOT NULL,
    "qtPrestacoes" INTEGER NOT NULL,
    "vlTotal" DOUBLE PRECISION NOT NULL,
    "vlTotalInBRL" TEXT NOT NULL,
    "cdProduto" TEXT NOT NULL,
    "dsProduto" TEXT NOT NULL,
    "cdCarteira" TEXT NOT NULL,
    "dsCarteira" TEXT NOT NULL,
    "nrProposta" TEXT NOT NULL,
    "nrPresta" TEXT NOT NULL,
    "tpPresta" TEXT NOT NULL,
    "nrSeqPre" TEXT NOT NULL,
    "dtVctPre" TIMESTAMP(3) NOT NULL,
    "vlPresta" DOUBLE PRECISION NOT NULL,
    "vlPrestaInBrl" TEXT NOT NULL,
    "vlMora" DOUBLE PRECISION NOT NULL,
    "vlMoraInBrl" TEXT NOT NULL,
    "vlMulta" DOUBLE PRECISION NOT NULL,
    "vlMultaInBrl" TEXT NOT NULL,
    "vlOutAcr" DOUBLE PRECISION NOT NULL,
    "vlOutAcrInBrl" TEXT NOT NULL,
    "vlIof" TEXT NOT NULL,
    "vlIofInBrl" TEXT NOT NULL,
    "vlDescon" DOUBLE PRECISION NOT NULL,
    "vlDesconInBrl" TEXT NOT NULL,
    "vlAtual" DOUBLE PRECISION NOT NULL,
    "vlAtualInBrl" TEXT NOT NULL,
    "idSituac" TEXT NOT NULL,
    "idSitVen" TEXT NOT NULL,
    "vlTotalInt" INTEGER NOT NULL,
    "vlPrestaInt" INTEGER NOT NULL,
    "vlMoraInt" INTEGER NOT NULL,
    "vlPrestaMora" INTEGER NOT NULL,
    "calculatedPresta" INTEGER NOT NULL,
    "calculatedPrestaMora" INTEGER NOT NULL,
    "vlMovimento" INTEGER NOT NULL,
    "isPrestaValid" BOOLEAN NOT NULL,
    "isPrestaMoraValid" BOOLEAN NOT NULL,
    "isMovimentoValid" BOOLEAN NOT NULL,
    "isCpfCnpjValid" BOOLEAN NOT NULL,
    "isValid" BOOLEAN NOT NULL,

    CONSTRAINT "Contract_pkey" PRIMARY KEY ("id")
);
